### ISSUE TITLE
Confusing functionality

### ISSUE THREAD

**Issue by mroberts1** [AndreasThinks/quarto-mastodon-comments#3]
I'm extremely confused about this extension. What exactly does it do? I see comments on the example page, but there is no field to add a comment on the page itself in the usual way (as with GitHub's utterances plugin for example).

I have a Mastodon account on another instance (merveilles.town) so am assuming that I can post replies from it on your page, but I can't figure out how to do that.

When I click on the reply icon on the example page it redirects me to your Fosstodon account, where I can post a reply to your post about the example page and it will apparently cross-post it back to this example page? But if I am always redirected to Mastodon, why not just keep the discussion on Mastodon?

Also, am I supposed to put this yaml code on the Quarto page where I want to embed Mastodon comments, or in a post on Mastodon itself? Do I put my own Mastodon ID in place of yours? What is the toot ID and where do I get the ID number from?

```
filters:
  - mastodon-comments
mastodon_comments:
  user: "AndreasThinks"
  host: "fosstodon.org"
  toot_id: "111995180253316042"
```
